### ISSUE TITLE
Flatiron's gauge of student activity is overinclusive

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/flatiron-kitchen#10]
Flatiron appears to regard a student as active with respect to a given lesson whenever that lesson is open in a tab on her browser, even if the student hasn't touched the tab for hours or days. This apparently results in various types of miscommunications, e.g.:

(1) The IM widget indicates that the student is working on Learn.co even though she is not. This creates confusion when the student doesn't respond.

(2) The "students working" message at the top of a lesson (i.e., students working _on that lesson_) is overinclusive. For instance, for many days, every lesson has told me that @anfjord is working on it. She must be a heck of a multi-tasker! (Perhaps this is a separate bug?)

(3) Flatiron's calculations of how long you spent on a given lesson are high. This bug may be less important now that those calculations are suppressed in the new UI.

**Comment by gj** [comment]
Hi @jonbf !

I've passed this along to our product team. Thank you for the feedback!
