### ISSUE TITLE
Lab Broken

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/flatiron-kitchen#2]
This lab is very broken. I can not get it to bundle correctly and when I do none of the basic parts of the tests will pass.

**Comment by pletcher** [comment]
Hi @Lukeghenco, thanks for reporting this issue. Could you paste the errors that you're seeing (or maybe one or two of them if there are many) here?

**Comment by scottcreynolds** [comment]
@pletcher I'm not having any problems with this

**Comment by pletcher** [comment]
@scottcreynolds Me neither. I'm going to close this for now, but if issues persist, anyone can reopen it.
